# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170805_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_lng',
            field=models.FloatField(default=0),
        ),
    ]
