# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='message',
            name='latlng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Message'),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
