# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_messagehistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
