# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_auto_20170805_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
