# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_auto_20170805_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
